FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.5_11_1.10.6_3.6.2

WORKDIR /app

# Copy project files
COPY build.sbt .
COPY project ./project

# Download dependencies (cached layer)
RUN sbt update

# Copy source code
COPY src ./src

# Run tests with coverage
CMD ["sbt", "coverage", "test", "coverageReport"]
